### ISSUE TITLE
Revert code editor to previous state

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-ui#1132]
### Please describe the feature that you want to propose

We first need to fix the issue with data loss, which will require a discussion with UXD, but the current code editor is making for quite a bad user experience.

Previously, we used to be able to:
1) write the code, and it would render immediately

Now, we the process looks like this:
1) click the edit button (once you know where it is)
2) write the code
3) press the save button (once you know where it is)
4) close the success notification to be able to then
5) press the close button on the modal

That's an additional 4-5 steps that we didn't have to do before.

Ideally, we will fix the issue with data loss and revert to the previous state of the code editor, maybe with some additional handling of validation.

**Comment by kahboom** [comment]
@lhein There is still data loss. So, rather than just removing invalid code right away and rendering the visualization, we are adding 4 steps and removing it anyway (and of course we don't have diff view yet so right now they still don't even know what will be removed), it's a terrible user experience.

**Comment by Delawen** [comment]
The current implemented editor was a good iteration towards a better user experience because now the user has to explicitly click save and read the warning that invalid data may be corrected automatically.

But I agree with @kahboom that this should not be the final form, this is just an iteration towards a better friendlier user experience. Adding so many clicks is discouraging.
