### ISSUE TITLE
Kaoto npm Package

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-ui#122]
As a user, I'd like to extend or embed Kaoto using a package published on the npm registry, and have access to the relevant typings (`IKaoto`).

**Comment by Delawen** [comment]
> The ability to embed Zimara means that there will not be an option to use generic extensions, only step extensions.

why?

**Comment by kahboom** [comment]
Because at the moment (at least, per the designs) the way you would access the generic extensions is through the sidebar. It would also be much easier to embed something that you wouldn't have to worry about the external application's navigation/routing, otherwise we open up a much more complicated setup. It's not impossible, of course, but maybe starting with a simpler implementation would be better.

**Comment by kahboom** [comment]
wait, why assign to me, I'd rather @mmelko did this one 😆

**Comment by Delawen** [comment]
Is this not the envelop thing?

**Comment by kahboom** [comment]
No this is for disabling the sidebar so that you can consume Kaoto in another application, for example, within an iFrame or as a federated module. With the sidebar and navbar that would not be very useful.

**Comment by kahboom** [comment]
Closing as the scope for this issue was never clearly defined. It ended up getting narrowed down to just needing typings for the Kaoto Step Extension API, which was implemented recently (though needs to be documented). We can't really publish Kaoto as an NPM package without the backend, so there's no point.

**Comment by kahboom** [comment]
Actually, reopening as we will be needing this for https://github.com/KaotoIO/vscode-kaoto/issues/27

**Comment by apupier** [comment]
The idea is to have s epcific component for Kaoto editor so that it can be reused. it will respect the "mulitplying architecture" coming from kie-tools. it will allow to reuse their framework.

A proof of concept has been provided here https://github.com/thiagoelg/kie-tools/tree/vscode-kaoto/packages/kaoto-editor

The current need is to migrate to KaotoIO organization for ease and maintenance and avoid having to match/block Kogito release planning.

Files has been moved to this specific repository: https://github.com/KaotoIO/kaoto-component-library

Identified tasks:
- use kie-tools 0.22.0 (currently based on an unreleased version between 0.21.0 and 0.21.1), see https://github.com/KaotoIO/kaoto-component-library/pull/1
- Fix compilation. Currently it is using pnpm and it doesn"'t compile outside of the structure of kie-tools. As build technology, I think we should migrate to npm (the lowest level) or yarn (the one used for most of other Kaoto projects). The webpack config will need to be updated to remove dependencies on some kie-tools artifact which are not published.
- Configure project to be able to publish so that it can be consumable from VS Code Kaoto

**Comment by apupier** [comment]
Package has been published on npmjs registry, see https://www.npmjs.com/package/@kaoto/kaoto-ui
