### ISSUE TITLE
Post request to backend on every character input to connector config

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto-ui#1339]
### Describe the Bug

The connector configuration seems to create big load to the backend. On every character input it is posting the newly inserted values to the backend.

### Steps to Reproduce the Bug or Issue

See recording

### Screenshots or Videos

![Peek 2023-02-28 17-29](https://user-images.githubusercontent.com/4180208/221917844-cc6c4477-03a6-4b9c-9fae-974873d60cbd.gif)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]

**Comment by kahboom** [comment]
Unfortunately that is just the way the UI was designed (before we had the sync button from the code editor it was meant to always be in sync between the JSON and YAML, with no in-between state). We can add a save button in there to prevent that and maybe as an enhancement, but otherwise it's technically not a bug by design.

**Comment by lhein** [comment]
Not a bug but maybe a performance issue later on?

**Comment by tplevko** [comment]
In case this is by design and we want to keep it, we could consider maybe adding the debounce for the input fields?

**Comment by apupier** [comment]
I'm wondering if implementing the debounce would help to mitigate this problem in VS Code: https://github.com/KaotoIO/vscode-kaoto/issues/210
