### ISSUE TITLE
Delete branch button sometimes hidden by another branch step

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto-ui#1379]
### Describe the Bug

The delete branch element is hidden behind another branch step element. See screenshot

### Steps to Reproduce the Bug or Issue

1. create several branches - ideally with multiple steps
2. Add a branch with single step 

### Screenshots or Videos

![Screenshot from 2023-03-03 14-24-00](https://user-images.githubusercontent.com/4180208/222732495-cdda4fa2-3c7e-4def-b257-6e1b4abf0bbc.png)

### Platform

- OS: [Linux]
- Browser: [Firefox]
- Version: [latest]

**Comment by kahboom** [comment]
I think this might actually be the same as #1277 , I thought the same thing but I _think_ it's not that it's covered, it's that there was an issue where the delete button wasn't being created.

To make matters more complicated, after that we also implemented #1143 which is tricky to tell from the UI if the branch can't be deleted because it has a minimum number of branches.

On a separate note: Why is the delete button showing on the right-hand edge of the step? 🤔  That could be a bug too..
