### ISSUE TITLE
Add new route in the code editor not reflected in the canvas after sync

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto-ui#2090]
### Describe the Bug

When users add new route in the code editor, this new route is not displayed in the canvas after the code sync. 

### Steps to Reproduce the Bug or Issue

1. create seceral camel routes in the code editor (add [] on new line)
2.  sync code changes
3. see no new routes were created

### Screenshots or Videos

![Peek 2023-07-03 10-46](https://github.com/KaotoIO/kaoto-ui/assets/4180208/8b60eb93-2a89-4899-b963-776dc982026a)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [latest]

**Comment by igarashitm** [comment]
It would be a same root cause with #2056 

The backend doesn't recognize `[]` as a route and just return empty integration JSON with this YAML. We have to either
1. Make both backend and frontend recognize `[]` as an empty route
2. Make backend generates at least `from` and `steps` for the empty route

https://github.com/KaotoIO/kaoto-ui/assets/265462/ea67953a-3673-4baf-ad7c-802004519a81

**Comment by lordrip** [comment]
@igarashitm I also think that (2) makes more sense :+1:
