### ISSUE TITLE
Unable to create new integration

### ISSUE THREAD

**Issue by fabriciomendes25** [KaotoIO/kaoto-ui#2101]
### Describe the Bug

On the last 1.1.0 or the nightly container build, there's no input field to enter the integration name.

![image](https://github.com/KaotoIO/kaoto-ui/assets/86064204/62641638-6dba-4102-a6e6-6f165806b16e)

Trying to deploy the image anyway leads to 405 error on the API. Probably because the name is undefined. 

![image](https://github.com/KaotoIO/kaoto-ui/assets/86064204/73e6f128-2cae-4e8b-9126-15d5b0cd606d)

Even in the source editor the name came to be an empty string

![image](https://github.com/KaotoIO/kaoto-ui/assets/86064204/4f5432e5-a4a9-4eda-a13b-d85cdad798c3)

### Steps to Reproduce the Bug or Issue

1. Checkout the v1.1.0-M1 tag 
2. Open KaotoUI
3. Open the network recorder
4. Create a new integration
5. Check the deployment POST request

### Platform

- OS: Windows 10
- Browser: Chrome
- Version: 114

**Comment by lordrip** [comment]
Hi @fabriciomendes25, thanks for reporting this, I'll take a look :ok_hand: 

In the meantime, are you able to deploy a route using the default name?

**Comment by lordrip** [comment]
> On the last 1.1.0 or the nightly container build, there's no input field to enter the integration name.

Almost forgot, as you mentioned, there's no input field for the integration name in the settings menu since the introduction of support for multiple routes, with that, a single input field won't work for multiple routes, that's why the interaction will change a bit.

In a nutshell, the idea would be to change the integration name using the `Routes List` directly, probably by showing a pencil icon that transforms the name into a text input.

![image](https://github.com/KaotoIO/kaoto-ui/assets/16512618/0eaf8286-b3d8-40b0-9e69-9b97399936aa)

This has not been developed yet, but it's planned to be tackled soon. :smiley:

**Comment by lordrip** [comment]
In addition to what I was mentioning, @igarashitm highlight an important topic around [names / description here](https://github.com/KaotoIO/kaoto-ui/issues/1795#issuecomment-1622136412):

**Comment by igarashitm** [comment]
Note that `name` is in slight different situation, where k8s `ObjectMeta` has `name` as a declared field so that you can put `name` into `metadata` directly - https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#objectmeta-v1-meta

| DSL | Per route | Per CRD/file |
| ------------- | ------------- | ------------- |
| Camel Route | `route/id` | N/A |
| Integration | `route/id` | `/metadata/name` |
| Kamelet | `/spec/template/id` | `/metadata/name` and `/spec/definition/title` |
| KameletBinding | N/A | `/metadata/name` |
