### ISSUE TITLE
Display Name and Value input fields right after add property button click

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto-ui#2169]
### Please describe the feature that you want to propose

This is a feedback/proposal for the Beans Configuration - would it be possible to show both fields - name and value, right after the add property button was clicked?  Same for the object property - could the buttons be displayed right after it was added?
The need to click outside the name input field to have the "value" input displayed makes user experience IMO a bit less pleasant.

![Peek 2023-07-20 11-56](https://github.com/KaotoIO/kaoto-ui/assets/4180208/43152558-0873-47ea-bc3b-422154a23efc)

**Comment by igarashitm** [comment]
We can add value input field there, but because of the placeholder to avoid invalid property (empty/duplicate name), it still needs an additional click to input the value, i.e.
1. commit new property name (1st click)
2. rerender created property row without placeholder 
3. focus on the value input field (2nd click)

We would need to remove uniforms and do manual form rendering in order to achieve this click saving.

**Comment by igarashitm** [comment]
It might be slightly intuitive to remove onBlur saving and add save/cancel button on the placeholder as well. With the manual save/cancel button, we can accept both name and value in the placeholder, i.e. move from name input to the value input in one click. It still needs to click the save button to save the property addition, so the number of clicking isn't really reducing, though.
