### ISSUE TITLE
Reduce container image size with multi-stage build

### ISSUE THREAD

**Issue by evanshortiss** [KaotoIO/kaoto-ui#254]
A colleague was downloading and running this frontend and commented that it was a very large container image pull. 

You folks might already be aware, but the image size could be reduced with a dockerfile similar to the example below. This reduced the image size from 2.65GB to 175MB in my test, and the React application loaded in my browser so I _think_ it doesn't break anything.

```dockerfile 
FROM node:16 as appbuild

WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

COPY . ./
RUN yarn install
RUN echo "KAOTO_API=http://localhost:8081" > ./.env
HEALTHCHECK --interval=3s --start-period=10s CMD curl --fail http://localhost:8080/ || exit 1

RUN yarn build

FROM nginx:latest
COPY --from=appbuild /app/dist/* /usr/share/nginx/html/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
```

I was curious about using [cached layers](https://nodejs.org/en/docs/guides/nodejs-docker-webapp/#creating-a-dockerfile) for the build, but ran into Yarn issues that I didn't really understand!

**Comment by Delawen** [comment]
I was a complete newbie generating node based images :) Thank you! Do you want to create a PR with this?

**Comment by evanshortiss** [comment]
@Delawen sure. Will do. Are you guys using Yarn to speed up builds BTW? I noticed that there's a Yarn cache checked in, but I don't know enough about Yarn to understand the different versions of it being specified in package.json. Is that why the `node_modules` are added to the PATH too?

**Comment by kahboom** [comment]
Thanks @evanshortiss, I'm happy to see this issue. I'm not surprised the container image is huge, as I've done literally nothing to prepare for it. 😆  Lots of things to do for a production build as well, including minification, concatenation, and tree shaking.

Regarding Yarn, we're using Yarn Berry (2.x., 3.x). I can switch to npm if it makes it easier for others to collaborate, but basically Yarn 1.x and NPM are similar in that they use `node_modules`, whereas Yarn Berry (2.x, 3.x) with Plug’n’Play uses a much smaller version of `node_modules` in `.yarn/cache`, which, unlike `node_modules`, _does_ get checked in, because the total file size is much smaller and ensures everyone is using the same version of everything, including Yarn.

It's also supposed to reduce the package installation time by around 70%. I will say, it doesn't seem to have gained as much momentum as quickly as I thought it would, probably due to breaking changes with Yarn 1.x, so if there is preference to use npm I'm happy to switch.

BTW there was a bug that was allowing `node_modules` to still get installed and breaks tests, so I've just fixed that.

Relevant links:
- [Yarn Berry: Why should you upgrade to Yarn modern?](https://yarnpkg.com/getting-started/qa#why-should-you-upgrade-to-yarn-modern)
- [Getting rid of node_modules with Yarn Plug'n'Play](https://www.freecodecamp.org/news/getting-rid-of-node-modules-with-yarn-plugn-play-a490e5e747d7/)
- [Hello Yarn 2, Goodbye node_modules](https://betterprogramming.pub/hello-yarn-2-goodbye-node-modules-21d97afc1a75)
- [State of Yarn 2 in 2021](https://blog.hao.dev/state-of-yarn-2-berry-in-2021)

**Comment by evanshortiss** [comment]
Related PR is #258
