### ISSUE TITLE
Only close Step Detail on selecting Step if it's the same Step

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-ui#543]
**Describe the bug**
When you click on a Step it opens the Step Detail. If you click it again, it closes the Step Detail. This was meant to be a convenience for the user, however, if the Step Detail is open and I click on a different step, it closes the Step Detail.

**To Reproduce**
1. Create or upload an `KameletBinding` with at least two Steps.
2. Click on one Step. The Step Detail opens.
3. Click another Step.
4. The Step Detail closes.

**Expected behavior**
It should a) keep the Step Detail open, and b) update the data in the Step Detail to show the selected Step's details instead.

**Screenshots**
No thank you.

**Desktop (please complete the following information):**
Everywhere

**Additional context**
For the first part of the problem (the Step Detail closing when it shouldn't), this should be fixable from the `/src/components/StepViews.tsx` and `Dashboard.tsx` components, particularly the `isPanelExpanded` flag. Check the `selectedStep` state. If it changes and is a different Step, the panel should not collapse. Or, it should only close if the Step clicked is the same as the `selectedStep`.

The second part should be fixed automatically once the first part is fixed, but this would need to be verified.

**Comment by lordrip** [comment]
Hi @kahboom, could it be possible that this issue is no longer relevant?

At the time of the writing, KaotoUI version `v0.6.1-dev` has a slightly different behavior as follows:

1. The user clicks on a step.
2. The Step Detail opens.
3. The user clicks on the same step. 
4. The Step Detail stays open.
5. The user clicks on another step.
6. The Step Detail stays open, now showing the details relevant for the selected step.

Also, I've prepared the following screencast to showcase the behavior:
[Screencast from 2023-02-08 16-59-49.webm](https://user-images.githubusercontent.com/16512618/217583713-56ad60e4-6a30-4c24-a463-366a3bf44daa.webm)

That being said, I kinda like this behavior, and probably would make sense to close the `Step Details` upon clicking on an empty area of the canvas as well :thinking:
