### ISSUE TITLE
[UX] Provide a "Delete" button for steps on canvas

### ISSUE THREAD

**Issue by lhein** [KaotoIO/kaoto-ui#675]
**Is your feature request related to a problem? Please describe.**
Adding new figures / steps to the canvas is really easy and can be done directly on the canvas which is quite convenient. Unfortunately to remove a figure from the canvas you have to click it to open the right side configuration panel and to click the "Delete" button there. 

**Describe the solution you'd like**
Can we add a "-" button to the figure analogue to the "+" one?

**Additional context**
![grafik](https://user-images.githubusercontent.com/435853/188118102-ac093cb1-e3a1-4653-8e8a-f1430c2979f2.png)

**Comment by kahboom** [comment]
@miram13 - As we discussed on our call earlier today, this is how I would approach this issue, but feel free to do it differently:

### Functionality
We already have a function to delete steps that can be reused (the same one we call when deleting a step from the Step Detail View) [here](https://github.com/KaotoIO/kaoto-ui/blob/main/src/components/Visualization.tsx#L174). However, for it to be reused we need to move `setIsPanelExpanded(false);` out of there (because we don't need to close the panel if we delete the step directly from the canvas).

1. I suggest that instead of calling `handleDeleteStep` directly as it does [here](https://github.com/KaotoIO/kaoto-ui/blob/main/src/components/Visualization.tsx#L267), you instead convert it to its own function like this:

```
() => {
  handleDeleteStep();
  setIsPanelExpanded(false);
}
```

2. Pass the `handleDeleteStep` method to the `VisualizationStep` component by adding a reference to it [here](https://github.com/KaotoIO/kaoto-ui/blob/main/src/components/Visualization.tsx#L137), just like we do with `step`.
3. Your IDE will complain because `IVizStepPropsNode` is an [interface](https://www.typescriptlang.org/docs/handbook/typescript-tooling-in-5-minutes.html#interfaces) in TypeScript, almost like a blueprint for what properties it allows, and it doesn't understand what is `handleDeleteStep`. You will have to edit that interface to also allow a function called `handleDeleteStep` or whatever you choose to call it. This is done from [here](https://github.com/KaotoIO/kaoto-ui/blob/main/src/%40kaoto/index.ts#L152). It could look something like this: `handleDeleteStep: () => void`.
4. Now you will have access to this function in the `VisualizationStep` component, like `data.handleDeleteStep()`. So you should create a function that handles clicking on the trashcan icon once you have it, something like, `const handleTrashClick = () => { // open a modal to confirm, or just call data.handleDeleteStep() directly };`.

### Styling/CSS
You can use a similar approach to how we do for the + button [here](https://github.com/KaotoIO/kaoto-ui/blob/main/src/components/VisualizationStep.tsx#L118) and there is some CSS to position it around the node, like [this](https://github.com/KaotoIO/kaoto-ui/blob/main/src/components/Visualization.css#L34).

### Bonus
Because this would allow users to delete without opening the Step Detail, it makes it really easy to make a mistake and delete a Step. We should consider adding a confirmation modal like we do for the toolbar [here](https://github.com/KaotoIO/kaoto-ui/blob/main/src/components/KaotoToolbar.tsx#L347), and call `data.handleDeleteStep()` from there. We can even use the same `ConfirmationModal` component.

Of course, you can always ping me and I'll be available for any questions. :)
